---

# define variables here that will not change
# Those are valid for all OS
#

__sap_general_preconfigure_etc_sysctl_sap_conf: /etc/sysctl.d/sap.conf

__sap_general_preconfigure_max_hostname_length: '13'
