---
# The following tasks are only included on the primary node!

- name: "SAP Pacemaker Hana - check constraint order HANA TOPOLOGY"
  shell: |
    pcs constraint order --full | grep "id:"| awk -F "id:" '{ print $2 }' | \
    grep order-SAPHanaTopology_{{ sap_ha_set_hana_sid }}_{{ sap_ha_set_hana_instance_number }}-clone-SAPHana
  register: sap_ha_set_hana_check_constraint_order_topology
  failed_when: false
  changed_when: false

- name: "SAP Pacemaker Hana - set ORDER Constraints"
  shell: |
    pcs constraint order \
    SAPHanaTopology_{{ sap_ha_set_hana_sid }}_{{ sap_ha_set_hana_instance_number }}-clone then \
    SAPHana_{{ sap_ha_set_hana_sid }}_{{ sap_ha_set_hana_instance_number }}-clone symmetrical=false
  when:
    - sap_ha_set_hana_check_constraint_order_topology.rc == 1

- name: "SAP Pacemaker Hana - check constraint colocation VIP with MASTER HANA"
  shell: |
    pcs constraint colocation --full | \
    grep colocation-vip_{{ sap_ha_set_hana_sid }}_{{ sap_ha_set_hana_instance_number }}_MASTER-SAPHana
  register: sap_ha_set_hana_check_constraint_collocation_vip_master
  failed_when: false
  changed_when: false
  when: sap_ha_set_hana_vip1 is defined

- name: "SAP Pacemaker Hana - Constraint: promote HANA then start VIP"
  shell: |
    pcs constraint colocation add \
    vip_{{ sap_ha_set_hana_sid }}_{{ sap_ha_set_hana_instance_number }}_MASTER \
    with master \
    SAPHana_{{ sap_ha_set_hana_sid }}_{{ sap_ha_set_hana_instance_number }}-clone 2000
    pcs constraint order promote \
    SAPHana_{{ sap_ha_set_hana_sid }}_{{ sap_ha_set_hana_instance_number }}-clone \
    then start \
    vip_{{ sap_ha_set_hana_sid }}_{{ sap_ha_set_hana_instance_number }}_MASTER
  when:
    - sap_ha_set_hana_check_constraint_collocation_vip_master.rc == 1
    - sap_ha_set_hana_vip1 is defined
