---

# vars file for sap_netweaver_preconfigure

__sap_netweaver_preconfigure_sapnotes:
  - "2526952"

__sap_netweaver_preconfigure_sapnotes_versions:
  - {number: '2526952', version: '5'}

__sap_netweaver_preconfigure_packages:
  - tuned-profiles-sap

__sap_netweaver_preconfigure_min_swap_space_mb: '20480'

__sap_netweaver_preconfigure_adobe_doc_services_packages:
  - autoconf.noarch
  - automake.noarch
  - cyrus-sasl.x86_64
  - expat.x86_64
  - fontconfig.x86_64
  - freetype.x86_64
  - glibc.x86_64
  - glibc-devel.x86_64
  - keyutils-libs.x86_64
  - krb5-libs.x86_64
  - libcom_err.x86_64
  - libgcc.x86_64
  - libidn.x86_64
  - libidn-devel.x86_64
  - libselinux.x86_64
  - libssh2.x86_64
  - libX11.x86_64
  - libXau.x86_64
  - libxcb.x86_64
  - nspr.x86_64
  - nss.x86_64
  - nss-softokn.x86_64
  - nss-softokn-freebl.x86_64
  - nss-util.x86_64
  - openldap.x86_64
  - openssl.x86_64
  - transfig.x86_64
  - zlib.x86_64
  - libuuid.x86_64
