---
# defaults file for sap_netweaver_preconfigure

# Perform an assertion run:
sap_netweaver_preconfigure_assert: no

# In case of an assertion run, if set to "yes", the role will abort for any assertion error:
sap_netweaver_preconfigure_assert_ignore_errors: no

sap_netweaver_preconfigure_min_swap_space_mb: "{{ __sap_netweaver_preconfigure_min_swap_space_mb }}"

sap_netweaver_preconfigure_fail_if_not_enough_swap_space_configured: yes

sap_netweaver_preconfigure_use_adobe_doc_services: no
