---
- name: "SAP Prepare Pacemaker - Enable firewall"
  ansible.builtin.systemd:
    service: firewalld.service
    state: started
    enabled: true

- name: "SAP Prepare Pacemaker - Configure firewall"
  ansible.builtin.firewalld:
    service: high-availability
    state: enabled
    immediate: yes
    permanent: yes

- name: "SAP Prepare Pacemaker - Immediately reload firewalld service"
  ansible.builtin.systemd:
    service: firewalld.service
    state: reloaded
