---
- name: "SAP Prepare Pacemaker - Pick up primary node name from definition"
  ansible.builtin.set_fact:
    __sap_ha_prepare_pacemaker_primary_node: "{{ item.node_name }}"
  when:
    - item.node_role is defined
    - item.node_role == 'primary'
  loop: "{{ sap_ha_prepare_pacemaker_cluster_nodes }}"
  loop_control:
    label: "{{ item.node_name }}"
  tags:
    - ha_software
    - ha_firewall
    - pacemaker
    - ha

- name: "SAP Prepare Pacemaker - Check if pcs package is installed"
  shell: |
    rpm -qa pcs
  args:
    executable: /bin/bash
  become: true
  become_user: root
  register: sap_ha_prepare_pacemaker_check_pcs
  changed_when: false
  tags:
    - ha_software
    - pacemaker
    - ha

- name: "SAP Prepare Pacemaker - Software Setup"
  include_tasks:
    file: software_setup.yml
    apply:
      tags:
        - ha_software
        - pacemaker
        - ha
  when:
    - sap_ha_prepare_pacemaker_check_pcs.rc != '0'
  tags:
    - ha_software
    - pacemaker
    - ha

- name: "SAP Prepare Pacemaker - Preconfig"
  include_tasks:
    file: preconfig.yml
    apply:
      tags:
        - pacemaker
        - ha
  tags:
    - pacemaker
    - ha

- name: "SAP Prepare Pacemaker - Include Firewall Tasks"
  include_tasks:
    file: configure_firewall.yml
    apply:
      tags:
        - ha_firewall
        - pacemaker
        - ha
  when:
    - (sap_hana_configure_firewall is defined and sap_hana_configure_firewall) or sap_ha_prepare_pacemaker_configure_firewall
  tags:
    - ha_firewall
    - pacemaker
    - ha

- name: "SAP Prepare Pacemaker - Check Cluster Status"
  shell: |
    pcs cluster status
  args:
    executable: /bin/bash
  become: true
  become_user: root
  register: sap_ha_prepare_pacemaker_check_cluster
  changed_when: false
  failed_when: false
  tags:
    - pacemaker
    - ha

- name: "SAP Prepare Pacemaker - Cluster Prepare"
  include_tasks:
    file: cluster_prepare.yml
    apply:
      tags:
        - pacemaker
        - ha
  when:
    - sap_ha_prepare_pacemaker_check_cluster.rc == 1
  tags:
    - pacemaker
    - ha
