---
# [A] Change hacluster password
- name: "SAP Prepare Pacemaker - Ensure password for hacluster is configured"
  ansible.builtin.user:
    name: hacluster
    password: "{{ sap_ha_prepare_pacemaker_hacluster_password | password_hash('sha512') }}"
