---
sap_ha_prepare_pacemaker_hacluster_password: "{{ sap_hana_hacluster_password }}"
sap_ha_prepare_pacemaker_cluster_nodes: "{{ sap_hana_cluster_nodes }}"
sap_ha_prepare_pacemaker_configure_firewall: no

sap_ha_prepare_pacemaker_rhsm_repos:
  - "rhel-{{ ansible_distribution_major_version }}-for-{{ ansible_architecture }}-highavailability-e4s-rpms"

sap_ha_prepare_pacemaker_packages:
  - pcs
  - pacemaker
  - nfs-utils
  - resource-agents-sap-hana
  - fence-agents-all
